// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqX54e0lQz8VaD1nKEjhmTgUuxQPb2D9Q',
    appId: '1:933056386075:web:f37ac77d961ca8894e94be',
    messagingSenderId: '933056386075',
    projectId: 'detection-e56dd',
    authDomain: 'detection-e56dd.firebaseapp.com',
    storageBucket: 'detection-e56dd.firebasestorage.app',
    measurementId: 'G-P0ZL9P7TWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD281ZH1fDzeR4okmOXkbehscvhusCm_Bs',
    appId: '1:933056386075:android:d143f068d1199e874e94be',
    messagingSenderId: '933056386075',
    projectId: 'detection-e56dd',
    storageBucket: 'detection-e56dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCisodLN1Bc8TY9F-0vv6RlcY3_ap4IBoI',
    appId: '1:933056386075:ios:07be8028702c00344e94be',
    messagingSenderId: '933056386075',
    projectId: 'detection-e56dd',
    storageBucket: 'detection-e56dd.firebasestorage.app',
    iosBundleId: 'com.example.obj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCisodLN1Bc8TY9F-0vv6RlcY3_ap4IBoI',
    appId: '1:933056386075:ios:07be8028702c00344e94be',
    messagingSenderId: '933056386075',
    projectId: 'detection-e56dd',
    storageBucket: 'detection-e56dd.firebasestorage.app',
    iosBundleId: 'com.example.obj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqX54e0lQz8VaD1nKEjhmTgUuxQPb2D9Q',
    appId: '1:933056386075:web:48bccf88d99983ee4e94be',
    messagingSenderId: '933056386075',
    projectId: 'detection-e56dd',
    authDomain: 'detection-e56dd.firebaseapp.com',
    storageBucket: 'detection-e56dd.firebasestorage.app',
    measurementId: 'G-TV0CWFDY8D',
  );
}
